services:
  app:
    build:
      context: ./
    container_name: backend_prev_heart
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - prev_heart_network

    depends_on:
      db:
        condition: service_healthy
    command: npm run start:docker

  db:
    image: postgres:17-alpine3.21
    container_name: pg_prev_heart
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myapp
    volumes:
      - db_dev:/var/lib/postgresql/data
    networks:
      - prev_heart_network

    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "myapp"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  prev_heart_network:
    driver: bridge

volumes:
  db_dev:
    driver: local