export const HEART_RATE_PROVIDER = Symbol('HEART_RATE_PROVIDER');
export const HEART_RATE_REPOSITORY = Symbol('HEART_RATE_REPOSITORY');
export const ALERT_NOTIFIER = Symbol('ALERT_NOTIFIER');
export const PUSH_TOKEN_REPOSITORY = Symbol('PUSH_TOKEN_REPOSITORY');
export const EXPO_PUSH_CLIENT = Symbol('EXPO_PUSH_CLIENT');

export const PROCESS_HEART_RATE_ALERT_SERVICE = Symbol(
  'PROCESS_HEART_RATE_ALERT_SERVICE',
);
